apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-containerrrrrr
          image: askyourmentors/yourmentors_fe:3
          ports:
            - containerPort: 80
